package sdk

// Code generated from apidoc metadata. DO NOT EDIT.

type APIDefinition struct {
	APIName      string
	MethodName   string
	RequestClass string
	Methods      []string
	Path         string
	Title        string
	Source       string
}

var APIDefinitions = []APIDefinition{
	{
		APIName:      "CdnHighDefenseIP_getArticleIP",
		MethodName:   "cdn_high_defense_ip_get_article_ip",
		RequestClass: "CdnHighDefenseIpGetArticleIpRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/ip.article.list",
		Title:        "加白IP列表",
		Source:       "common.php",
	},
	{
		APIName:      "DnsDomain_getDomainList",
		MethodName:   "dns_domain_get_domain_list",
		RequestClass: "DnsDomainGetDomainListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/domains",
		Title:        "查询域名列表",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_addDomain",
		MethodName:   "dns_domain_add_domain",
		RequestClass: "DnsDomainAddDomainRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/domains",
		Title:        "添加域名",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_batchAddDomains",
		MethodName:   "dns_domain_batch_add_domains",
		RequestClass: "DnsDomainBatchAddDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/domains_batch_add",
		Title:        "批量添加域名",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_batchDeleteDomains",
		MethodName:   "dns_domain_batch_delete_domains",
		RequestClass: "DnsDomainBatchDeleteDomainsRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/sdns/domains_batch_delete",
		Title:        "批量删除域名",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_getDomainStat",
		MethodName:   "dns_domain_get_domain_stat",
		RequestClass: "DnsDomainGetDomainStatRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/domains/stat",
		Title:        "查询域名统计",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_getDomainServers",
		MethodName:   "dns_domain_get_domain_servers",
		RequestClass: "DnsDomainGetDomainServersRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/domains/servers",
		Title:        "查询域名服务器",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_getTasksList",
		MethodName:   "dns_domain_get_tasks_list",
		RequestClass: "DnsDomainGetTasksListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/tasks",
		Title:        "查询任务列表",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "DnsDomain_getTaskDetail",
		MethodName:   "dns_domain_get_task_detail",
		RequestClass: "DnsDomainGetTaskDetailRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/tasks/detail",
		Title:        "查询任务详情",
		Source:       "dns/dns_domain.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_getGroupList",
		MethodName:   "cloud_dns_domain_group_get_group_list",
		RequestClass: "CloudDnsDomainGroupGetGroupListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/domains/groups",
		Title:        "查询域名分组列表",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_addGroup",
		MethodName:   "cloud_dns_domain_group_add_group",
		RequestClass: "CloudDnsDomainGroupAddGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/domains/groups",
		Title:        "添加域名分组",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_updateGroup",
		MethodName:   "cloud_dns_domain_group_update_group",
		RequestClass: "CloudDnsDomainGroupUpdateGroupRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/sdns/domains/groups",
		Title:        "更新域名分组",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_deleteGroup",
		MethodName:   "cloud_dns_domain_group_delete_group",
		RequestClass: "CloudDnsDomainGroupDeleteGroupRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/sdns/domains/groups",
		Title:        "删除域名分组",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_getGroupRecordList",
		MethodName:   "cloud_dns_domain_group_get_group_record_list",
		RequestClass: "CloudDnsDomainGroupGetGroupRecordListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/records/groups",
		Title:        "查询域名分组记录列表",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_saveDomainToGroup",
		MethodName:   "cloud_dns_domain_group_save_domain_to_group",
		RequestClass: "CloudDnsDomainGroupSaveDomainToGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records/groups_relations",
		Title:        "域名分组记录操作",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_getGroupDomainList",
		MethodName:   "cloud_dns_domain_group_get_group_domain_list",
		RequestClass: "CloudDnsDomainGroupGetGroupDomainListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/cloud.dns.domain.group.domain.list",
		Title:        "查询域名组关联的域名列表",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "CloudDns_DomainGroup_getGroupUndistributedDomainList",
		MethodName:   "cloud_dns_domain_group_get_group_undistributed_domain_list",
		RequestClass: "CloudDnsDomainGroupGetGroupUndistributedDomainListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/cloud.dns.domain.group.undistributed.domain.list",
		Title:        "查询未关联域名组的域名列表",
		Source:       "dns/dns_domain_group.php",
	},
	{
		APIName:      "DnsDomainRecords_getRecordTypes",
		MethodName:   "dns_domain_records_get_record_types",
		RequestClass: "DnsDomainRecordsGetRecordTypesRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/types",
		Title:        "列出支持的记录类型",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_getRecordList",
		MethodName:   "dns_domain_records_get_record_list",
		RequestClass: "DnsDomainRecordsGetRecordListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/records",
		Title:        "查询域名记录列表",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_addRecord",
		MethodName:   "dns_domain_records_add_record",
		RequestClass: "DnsDomainRecordsAddRecordRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records",
		Title:        "添加域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_batchAddRecords",
		MethodName:   "dns_domain_records_batch_add_records",
		RequestClass: "DnsDomainRecordsBatchAddRecordsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records_batch_add",
		Title:        "批量添加域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_editRecord",
		MethodName:   "dns_domain_records_edit_record",
		RequestClass: "DnsDomainRecordsEditRecordRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/sdns/records",
		Title:        "编辑域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_batchPauseRecords",
		MethodName:   "dns_domain_records_batch_pause_records",
		RequestClass: "DnsDomainRecordsBatchPauseRecordsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records_batch_pause",
		Title:        "批量暂停域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_batchEnableRecords",
		MethodName:   "dns_domain_records_batch_enable_records",
		RequestClass: "DnsDomainRecordsBatchEnableRecordsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records_batch_enable",
		Title:        "批量启用域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_deleteRecord",
		MethodName:   "dns_domain_records_delete_record",
		RequestClass: "DnsDomainRecordsDeleteRecordRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/sdns/records",
		Title:        "删除域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_importRecords",
		MethodName:   "dns_domain_records_import_records",
		RequestClass: "DnsDomainRecordsImportRecordsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records_import",
		Title:        "导入域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_exportRecords",
		MethodName:   "dns_domain_records_export_records",
		RequestClass: "DnsDomainRecordsExportRecordsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records_export",
		Title:        "导出域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_getLines",
		MethodName:   "dns_domain_records_get_lines",
		RequestClass: "DnsDomainRecordsGetLinesRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/lines",
		Title:        "列出线路",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_batchDeleteRecords",
		MethodName:   "dns_domain_records_batch_delete_records",
		RequestClass: "DnsDomainRecordsBatchDeleteRecordsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records_batch_delete",
		Title:        "批量删除域名记录",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_getRecordGroupsList",
		MethodName:   "dns_domain_records_get_record_groups_list",
		RequestClass: "DnsDomainRecordsGetRecordGroupsListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/sdns/records/groups",
		Title:        "查询记录组列表",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_addRecordGroup",
		MethodName:   "dns_domain_records_add_record_group",
		RequestClass: "DnsDomainRecordsAddRecordGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records/groups",
		Title:        "添加记录组",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_addRecordGroupRelations",
		MethodName:   "dns_domain_records_add_record_group_relations",
		RequestClass: "DnsDomainRecordsAddRecordGroupRelationsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/sdns/records/groups_relations",
		Title:        "添加记录组关系",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "DnsDomainRecords_deleteRecordGroup",
		MethodName:   "dns_domain_records_delete_record_group",
		RequestClass: "DnsDomainRecordsDeleteRecordGroupRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/sdns/records/groups",
		Title:        "删除记录组",
		Source:       "dns/dns_domain_records.php",
	},
	{
		APIName:      "UserIp_userIpList",
		MethodName:   "user_ip_user_ip_list",
		RequestClass: "UserIpUserIpListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/user.ip.list",
		Title:        "获取 IP 列表",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_userIpAdd",
		MethodName:   "user_ip_user_ip_add",
		RequestClass: "UserIpUserIpAddRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/user.ip.add",
		Title:        "新增 IP 列表",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_userIpSave",
		MethodName:   "user_ip_user_ip_save",
		RequestClass: "UserIpUserIpSaveRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/user.ip.save",
		Title:        "更新 IP 列表",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_userIpDel",
		MethodName:   "user_ip_user_ip_del",
		RequestClass: "UserIpUserIpDelRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/user.ip.del",
		Title:        "删除 IP 列表",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_listUserIpItem",
		MethodName:   "user_ip_list_user_ip_item",
		RequestClass: "UserIpListUserIpItemRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/user.ip.item.list",
		Title:        "IP 项列表",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_AddUserIpItem",
		MethodName:   "user_ip_add_user_ip_item",
		RequestClass: "UserIpAddUserIpItemRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/user.ip.item.text.save",
		Title:        "新增 IP 项",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_UpdateUserIpItem",
		MethodName:   "user_ip_update_user_ip_item",
		RequestClass: "UserIpUpdateUserIpItemRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/user.ip.item.edit",
		Title:        "编辑 IP 项",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_BatchDeleteUserIpItem",
		MethodName:   "user_ip_batch_delete_user_ip_item",
		RequestClass: "UserIpBatchDeleteUserIpItemRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/user.ip.item.del",
		Title:        "删除 IP 项",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_DeleteAllUserIpItem",
		MethodName:   "user_ip_delete_all_user_ip_item",
		RequestClass: "UserIpDeleteAllUserIpItemRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/user.ip.item.all",
		Title:        "删除所有 IP 项",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_CopyUserIp",
		MethodName:   "user_ip_copy_user_ip",
		RequestClass: "UserIpCopyUserIpRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/user.ip.copy",
		Title:        "复制 IP 列表",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "UserIp_FileSaveIpItem",
		MethodName:   "user_ip_file_save_ip_item",
		RequestClass: "UserIpFileSaveIpItemRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/user.ip.item.file.save",
		Title:        "上传 IP 文件",
		Source:       "ip/scdn_user_ip_intel.php",
	},
	{
		APIName:      "service_batch_ListTask",
		MethodName:   "service_batch_list_task",
		RequestClass: "ServiceBatchListTaskRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/task/list",
		Title:        "查询任务列表",
		Source:       "scdn/common/scdn_domain_batch_task.php",
	},
	{
		APIName:      "service_batch_ListSubTask",
		MethodName:   "service_batch_list_sub_task",
		RequestClass: "ServiceBatchListSubTaskRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/subtask/list",
		Title:        "查询子任务列表",
		Source:       "scdn/common/scdn_domain_batch_task.php",
	},
	{
		APIName:      "WebCdnCleanCache_getCacheList",
		MethodName:   "web_cdn_clean_cache_get_cache_list",
		RequestClass: "WebCdnCleanCacheGetCacheListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.Domain.DashBoard.getCache",
		Title:        "缓存清理可用余额查询",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "WebCdnCleanCache_saveCache",
		MethodName:   "web_cdn_clean_cache_save_cache",
		RequestClass: "WebCdnCleanCacheSaveCacheRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/Web.Domain.DashBoard.saveCache",
		Title:        "提交缓存清理任务",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "WebCdnCleanCache_getTaskList",
		MethodName:   "web_cdn_clean_cache_get_task_list",
		RequestClass: "WebCdnCleanCacheGetTaskListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.Domain.DashBoard.cache.clean.list",
		Title:        "查询缓存清理任务列表",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "WebCdnCleanCache_getTaskDetail",
		MethodName:   "web_cdn_clean_cache_get_task_detail",
		RequestClass: "WebCdnCleanCacheGetTaskDetailRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.Domain.DashBoard.cache.clean.detail",
		Title:        "查询缓存清理任务详情",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "WebCdnPreheatCache_getPreheatCacheQuota",
		MethodName:   "web_cdn_preheat_cache_get_preheat_cache_quota",
		RequestClass: "WebCdnPreheatCacheGetPreheatCacheQuotaRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.Domain.DashBoard.get.preheat.cache.list",
		Title:        "缓存预热可用余额查询",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "WebCdnPreheatCache_getPreheatCacheList",
		MethodName:   "web_cdn_preheat_cache_get_preheat_cache_list",
		RequestClass: "WebCdnPreheatCacheGetPreheatCacheListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.Domain.DashBoard.get.preheat.cache.new.list",
		Title:        "查询预热任务列表",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "WebCdnPreheatCache_savePreheatCache",
		MethodName:   "web_cdn_preheat_cache_save_preheat_cache",
		RequestClass: "WebCdnPreheatCacheSavePreheatCacheRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.Domain.DashBoard.save.preheat.cache",
		Title:        "提交预热任务",
		Source:       "scdn/common/scdn_domain_cache.php",
	},
	{
		APIName:      "Oplog_info",
		MethodName:   "oplog_info",
		RequestClass: "OplogInfoRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/oplog.info",
		Title:        "查询操作日志详情",
		Source:       "scdn/common/scdn_oplog.php",
	},
	{
		APIName:      "Oplog_map",
		MethodName:   "oplog_map",
		RequestClass: "OplogMapRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/oplog.map",
		Title:        "操作日志数据映射",
		Source:       "scdn/common/scdn_oplog.php",
	},
	{
		APIName:      "Oplog_getOplogs",
		MethodName:   "oplog_get_oplogs",
		RequestClass: "OplogGetOplogsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/oplog.list",
		Title:        "查询操作日志列表",
		Source:       "scdn/common/scdn_oplog.php",
	},
	{
		APIName:      "CaCertificateSelf_addCa",
		MethodName:   "ca_certificate_self_add_ca",
		RequestClass: "CaCertificateSelfAddCaRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.ca.self.add",
		Title:        "上传证书",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "Batch_caList",
		MethodName:   "batch_ca_list",
		RequestClass: "BatchCaListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.Domain.batch.ca.list",
		Title:        "查询域名证书列表",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_saveTextCaInfo",
		MethodName:   "ca_certificate_self_save_text_ca_info",
		RequestClass: "CaCertificateSelfSaveTextCaInfoRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.ca.text.save",
		Title:        "新增证书",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_editCaInfo",
		MethodName:   "ca_certificate_self_edit_ca_info",
		RequestClass: "CaCertificateSelfEditCaInfoRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.ca.info.edit",
		Title:        "编辑证书",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_listCa",
		MethodName:   "ca_certificate_self_list_ca",
		RequestClass: "CaCertificateSelfListCaRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.ca.self.list",
		Title:        "查询证书列表",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_caExport",
		MethodName:   "ca_certificate_self_ca_export",
		RequestClass: "CaCertificateSelfCaExportRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.ca.self.export",
		Title:        "导出证书",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_batchOperatSsl",
		MethodName:   "ca_certificate_self_batch_operat_ssl",
		RequestClass: "CaCertificateSelfBatchOperatSslRequest",
		Methods:      []string{"GET", "POST"},
		Path:         "/api/v5/Web.ca.batch.operat",
		Title:        "批量证书绑定域名",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_delCa",
		MethodName:   "ca_certificate_self_del_ca",
		RequestClass: "CaCertificateSelfDelCaRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/Web.ca.self.del",
		Title:        "删除证书",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_getCaDetail",
		MethodName:   "ca_certificate_self_get_ca_detail",
		RequestClass: "CaCertificateSelfGetCaDetailRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.ca.self",
		Title:        "查询证书详情",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateSelf_editCaName",
		MethodName:   "ca_certificate_self_edit_ca_name",
		RequestClass: "CaCertificateSelfEditCaNameRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.ca.self.editcaname",
		Title:        "修改证书名称",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateApply_addApplyCa",
		MethodName:   "ca_certificate_apply_add_apply_ca",
		RequestClass: "CaCertificateApplyAddApplyCaRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Web.ca.apply.add",
		Title:        "申购证书",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "CaCertificateApply_getAddByNsSetting",
		MethodName:   "ca_certificate_apply_get_add_by_ns_setting",
		RequestClass: "CaCertificateApplyGetAddByNsSettingRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Web.ca.apply.getAddByNsSetting",
		Title:        "获取未接入证书申购授权记录",
		Source:       "scdn/domain/scdn_domain_cert.php",
	},
	{
		APIName:      "DomainGroup_saveGroup",
		MethodName:   "domain_group_save_group",
		RequestClass: "DomainGroupSaveGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/web.domain.group.save",
		Title:        "修改域名组",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_getGroupList",
		MethodName:   "domain_group_get_group_list",
		RequestClass: "DomainGroupGetGroupListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/web.domain.group.list",
		Title:        "查询域名组列表",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_delGroup",
		MethodName:   "domain_group_del_group",
		RequestClass: "DomainGroupDelGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/web.domain.group.del",
		Title:        "删除域名组",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_getGroupDomainList",
		MethodName:   "domain_group_get_group_domain_list",
		RequestClass: "DomainGroupGetGroupDomainListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/web.domain.group.domain.list",
		Title:        "查询已绑定域名组的域名列表",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_ggtUndistributedDomainList",
		MethodName:   "domain_group_ggt_undistributed_domain_list",
		RequestClass: "DomainGroupGgtUndistributedDomainListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/web.domain.group.undistributed.domain.list",
		Title:        "查询未绑定域名组的域名列表",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_addGroup",
		MethodName:   "domain_group_add_group",
		RequestClass: "DomainGroupAddGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/web.domain.group.add",
		Title:        "添加域名组",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_saveDomainToGroup",
		MethodName:   "domain_group_save_domain_to_group",
		RequestClass: "DomainGroupSaveDomainToGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/web.domain.group.domain.save",
		Title:        "域名绑定域名组",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_getGroupInfo",
		MethodName:   "domain_group_get_group_info",
		RequestClass: "DomainGroupGetGroupInfoRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/web.domain.group.info",
		Title:        "查询域名组详情",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "DomainGroup_moveDomain",
		MethodName:   "domain_group_move_domain",
		RequestClass: "DomainGroupMoveDomainRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/web.domain.group.move_domain",
		Title:        "迁移域名组内域名",
		Source:       "scdn/domain/scdn_domain_group.php",
	},
	{
		APIName:      "ListDomains",
		MethodName:   "list_domains",
		RequestClass: "ListDomainsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/domains",
		Title:        "列出域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "AddDomains",
		MethodName:   "add_domains",
		RequestClass: "AddDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains",
		Title:        "添加域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "UpdateDomains",
		MethodName:   "update_domains",
		RequestClass: "UpdateDomainsRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/domains",
		Title:        "更新域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "BindDomainCert",
		MethodName:   "bind_domain_cert",
		RequestClass: "BindDomainCertRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/bind_cert",
		Title:        "绑定域名证书",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "UnBindDomainCert",
		MethodName:   "un_bind_domain_cert",
		RequestClass: "UnBindDomainCertRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/unbind_cert",
		Title:        "解绑域名证书",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "DeleteDomains",
		MethodName:   "delete_domains",
		RequestClass: "DeleteDomainsRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/domains",
		Title:        "删除域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "DisableDomains",
		MethodName:   "disable_domains",
		RequestClass: "DisableDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains_disable",
		Title:        "禁用域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "EnableDomains",
		MethodName:   "enable_domains",
		RequestClass: "EnableDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains_enable",
		Title:        "启用域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "RefreshDomainsAccess",
		MethodName:   "refresh_domains_access",
		RequestClass: "RefreshDomainsAccessRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/access_refresh",
		Title:        "刷新域名接入状态",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "ExportDomains",
		MethodName:   "export_domains",
		RequestClass: "ExportDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/domains_export",
		Title:        "导出域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "AddOrigins",
		MethodName:   "add_origins",
		RequestClass: "AddOriginsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/origins",
		Title:        "添加源站",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "UpdateOrigins",
		MethodName:   "update_origins",
		RequestClass: "UpdateOriginsRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/domains/origins",
		Title:        "更新源站",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "DeleteOrigins",
		MethodName:   "delete_origins",
		RequestClass: "DeleteOriginsRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/domains/origins",
		Title:        "删除源站",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "ListOrigins",
		MethodName:   "list_origins",
		RequestClass: "ListOriginsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/domains/origins",
		Title:        "列出源站",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "SwitchDomainNodes",
		MethodName:   "switch_domain_nodes",
		RequestClass: "SwitchDomainNodesRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/nodes_switch",
		Title:        "切换域名节点",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "SwitchDomainAccessMode",
		MethodName:   "switch_domain_access_mode",
		RequestClass: "SwitchDomainAccessModeRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/access_switch",
		Title:        "切换域名接入模式",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "UpdateDomainBaseSettings",
		MethodName:   "update_domain_base_settings",
		RequestClass: "UpdateDomainBaseSettingsRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/domains/base_settings",
		Title:        "更新域名基础设置",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "GetDomainBaseSettings",
		MethodName:   "get_domain_base_settings",
		RequestClass: "GetDomainBaseSettingsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/domains/base_settings",
		Title:        "获取域名基础设置",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "ListBriefDomains",
		MethodName:   "list_brief_domains",
		RequestClass: "ListBriefDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/brief_domains",
		Title:        "列出简要域名",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "GetDomainTemplates",
		MethodName:   "get_domain_templates",
		RequestClass: "GetDomainTemplatesRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/domains/templates",
		Title:        "获取域名模板",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "AccessInfoDownload",
		MethodName:   "access_info_download",
		RequestClass: "AccessInfoDownloadRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/domains/access_info_download",
		Title:        "批量添加域名任务，已添加域名接入信息下载",
		Source:       "scdn/domain/scdn_domain_v5_domain.php",
	},
	{
		APIName:      "OriginGroup_getOriginGroupList",
		MethodName:   "origin_group_get_origin_group_list",
		RequestClass: "OriginGroupGetOriginGroupListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/origin_groups",
		Title:        "查询源站组列表",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_getOriginGroupInfo",
		MethodName:   "origin_group_get_origin_group_info",
		RequestClass: "OriginGroupGetOriginGroupInfoRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/origin_groups/detail",
		Title:        "查询源站组详情",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_addOriginGroup",
		MethodName:   "origin_group_add_origin_group",
		RequestClass: "OriginGroupAddOriginGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/origin_groups",
		Title:        "添加源站组",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_updateOriginGroup",
		MethodName:   "origin_group_update_origin_group",
		RequestClass: "OriginGroupUpdateOriginGroupRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/origin_groups",
		Title:        "修改源站组",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_delOriginGroup",
		MethodName:   "origin_group_del_origin_group",
		RequestClass: "OriginGroupDelOriginGroupRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/origin_groups",
		Title:        "删除源站组",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_bindOriginGroupToDomains",
		MethodName:   "origin_group_bind_origin_group_to_domains",
		RequestClass: "OriginGroupBindOriginGroupToDomainsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/origin_groups/domains_bind",
		Title:        "绑定源站组到域名",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_getAllOriginGroups",
		MethodName:   "origin_group_get_all_origin_groups",
		RequestClass: "OriginGroupGetAllOriginGroupsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/origin_groups/all",
		Title:        "查询所有源站组列表(用于域名配置选择)",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "OriginGroup_copyOriginGroup",
		MethodName:   "origin_group_copy_origin_group",
		RequestClass: "OriginGroupCopyOriginGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/origin_groups/copy",
		Title:        "复制源站组到域名",
		Source:       "scdn/domain/scdn_origin_group.php",
	},
	{
		APIName:      "FireWallReport_getBlockList",
		MethodName:   "fire_wall_report_get_block_list",
		RequestClass: "FireWallReportGetBlockListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.report.block.list",
		Title:        "SCDN拦截统计",
		Source:       "scdn/statistical/scdn_dataapi.php",
	},
	{
		APIName:      "FireWallReport_getBlockDetails",
		MethodName:   "fire_wall_report_get_block_details",
		RequestClass: "FireWallReportGetBlockDetailsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.report.block.details",
		Title:        "查询SCDN拦截详情",
		Source:       "scdn/statistical/scdn_dataapi.php",
	},
	{
		APIName:      "FireWallReport_getPackageBlockList",
		MethodName:   "fire_wall_report_get_package_block_list",
		RequestClass: "FireWallReportGetPackageBlockListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.report.package.block.list",
		Title:        "四层拦截统计",
		Source:       "scdn/statistical/scdn_dataapi.php",
	},
	{
		APIName:      "FireWallReport_getPackageBlockDetails",
		MethodName:   "fire_wall_report_get_package_block_details",
		RequestClass: "FireWallReportGetPackageBlockDetailsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.report.package.block.details",
		Title:        "查询四层拦截详情",
		Source:       "scdn/statistical/scdn_dataapi.php",
	},
	{
		APIName:      "cc_qps_max",
		MethodName:   "cc_qps_max",
		RequestClass: "CcQpsMaxRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cc.qps.max",
		Title:        "查询CC攻击最大QPS",
		Source:       "scdn/statistical/scdn_dataapi_cc.php",
	},
	{
		APIName:      "cc_attack_times",
		MethodName:   "cc_attack_times",
		RequestClass: "CcAttackTimesRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cc.attack.times",
		Title:        "查询CC攻击次数",
		Source:       "scdn/statistical/scdn_dataapi_cc.php",
	},
	{
		APIName:      "cc_times_line",
		MethodName:   "cc_times_line",
		RequestClass: "CcTimesLineRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cc.times.line",
		Title:        "查询CC攻击趋势",
		Source:       "scdn/statistical/scdn_dataapi_cc.php",
	},
	{
		APIName:      "cc_report_stats",
		MethodName:   "cc_report_stats",
		RequestClass: "CcReportStatsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cc.report.stats",
		Title:        "统计CC数据",
		Source:       "scdn/statistical/scdn_dataapi_cc.php",
	},
	{
		APIName:      "cdn_domain_uaisp_distribute",
		MethodName:   "cdn_domain_uaisp_distribute",
		RequestClass: "CdnDomainUaispDistributeRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.uaisp.distribute",
		Title:        "UA、ISP分布",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_country_distribute",
		MethodName:   "cdn_domain_country_distribute",
		RequestClass: "CdnDomainCountryDistributeRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.country.distribute",
		Title:        "国家分布",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_province_distribute",
		MethodName:   "cdn_domain_province_distribute",
		RequestClass: "CdnDomainProvinceDistributeRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.province.distribute",
		Title:        "省份分布",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_status_distribute",
		MethodName:   "cdn_domain_status_distribute",
		RequestClass: "CdnDomainStatusDistributeRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.status.distribute",
		Title:        "状态码分布",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_node_flow_bandwidth",
		MethodName:   "cdn_domain_node_flow_bandwidth",
		RequestClass: "CdnDomainNodeFlowBandwidthRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.node.flow.bandwidth",
		Title:        "回源、命中缓存流量带宽趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_node_flow_bandwidth_cn2",
		MethodName:   "cdn_domain_node_flow_bandwidth_cn2",
		RequestClass: "CdnDomainNodeFlowBandwidthCn2Request",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.node.flow.bandwidth.cn2",
		Title:        "国内、海外、cn2流量带宽趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_node_flow_bandwidth_node",
		MethodName:   "cdn_domain_node_flow_bandwidth_node",
		RequestClass: "CdnDomainNodeFlowBandwidthNodeRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.node.flow.bandwidth.node",
		Title:        "各个节点的流量带宽趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "domainTimes",
		MethodName:   "domain_times",
		RequestClass: "DomainTimesRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.times",
		Title:        "域名访问次数趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "domainQps",
		MethodName:   "domain_qps",
		RequestClass: "DomainQpsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.qps",
		Title:        "域名QPS趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_flow_line",
		MethodName:   "cdn_domain_flow_line",
		RequestClass: "CdnDomainFlowLineRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.flow.line",
		Title:        "根据节点类型查流量趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_bandwidth_line",
		MethodName:   "cdn_domain_bandwidth_line",
		RequestClass: "CdnDomainBandwidthLineRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.bandwidth.line",
		Title:        "根据节点类型查带宽趋势",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_bandwidth_95",
		MethodName:   "cdn_domain_bandwidth_95",
		RequestClass: "CdnDomainBandwidth95Request",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.bandwidth_95",
		Title:        "根据节点类型查95带宽",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_pvtimes",
		MethodName:   "cdn_domain_pvtimes",
		RequestClass: "CdnDomainPvtimesRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.pvtimes",
		Title:        "域名PV次数",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_flow_top",
		MethodName:   "cdn_domain_flow_top",
		RequestClass: "CdnDomainFlowTopRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.flow.top",
		Title:        "域名流量TOP",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_bandwidth_top",
		MethodName:   "cdn_domain_bandwidth_top",
		RequestClass: "CdnDomainBandwidthTopRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.bandwidth.top",
		Title:        "域名带宽TOP",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_times_top",
		MethodName:   "cdn_domain_times_top",
		RequestClass: "CdnDomainTimesTopRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.times.top",
		Title:        "域名访问次数TOP",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_times_top_es",
		MethodName:   "cdn_domain_times_top_es",
		RequestClass: "CdnDomainTimesTopEsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.times.top.es",
		Title:        "域名访问次数TOP(ES)",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_url_top",
		MethodName:   "cdn_domain_url_top",
		RequestClass: "CdnDomainUrlTopRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.url.top",
		Title:        "热门URL",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_referer_top",
		MethodName:   "cdn_domain_referer_top",
		RequestClass: "CdnDomainRefererTopRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.referer.top",
		Title:        "热门REFERER",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_status_top_download",
		MethodName:   "cdn_domain_status_top_download",
		RequestClass: "CdnDomainStatusTopDownloadRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.status.top.download",
		Title:        "状态码下载",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_bandwidth_download",
		MethodName:   "cdn_domain_bandwidth_download",
		RequestClass: "CdnDomainBandwidthDownloadRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.bandwidth.download",
		Title:        "域名带宽使用下载",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "cdn_domain_flow_download",
		MethodName:   "cdn_domain_flow_download",
		RequestClass: "CdnDomainFlowDownloadRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.cdn.domain.flow.download",
		Title:        "域名流量使用下载",
		Source:       "scdn/statistical/scdn_dataapi_scdn.php",
	},
	{
		APIName:      "tcp_bandwidth",
		MethodName:   "tcp_bandwidth",
		RequestClass: "TcpBandwidthRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.tcp.bandwidth",
		Title:        "查询TCP带宽数据",
		Source:       "scdn/statistical/scdn_dataapi_tcp.php",
	},
	{
		APIName:      "tcp_cc_flaw",
		MethodName:   "tcp_cc_flaw",
		RequestClass: "TcpCcFlawRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/statistic.tjkd.plus.tcp.cc.flaw",
		Title:        "查询TCP流量数据",
		Source:       "scdn/statistical/scdn_dataapi_tcp.php",
	},
	{
		APIName:      "waf_attack_times",
		MethodName:   "waf_attack_times",
		RequestClass: "WafAttackTimesRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.attack.times",
		Title:        "WAF攻击次数",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_report_stats",
		MethodName:   "waf_report_stats",
		RequestClass: "WafReportStatsRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.report.stats",
		Title:        "WAF数据统计",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_webshell_event_list",
		MethodName:   "waf_webshell_event_list",
		RequestClass: "WafWebshellEventListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.webshell.event.list",
		Title:        "入侵事件",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_webshell_event_detail",
		MethodName:   "waf_webshell_event_detail",
		RequestClass: "WafWebshellEventDetailRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.webshell.event.detail",
		Title:        "入侵事件详情",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_attack_event_list",
		MethodName:   "waf_attack_event_list",
		RequestClass: "WafAttackEventListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.attack.event.list",
		Title:        "定向攻击事件",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_attack_event_detail",
		MethodName:   "waf_attack_event_detail",
		RequestClass: "WafAttackEventDetailRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.attack.event.detail",
		Title:        "定向攻击事件详情",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_scan_event_list",
		MethodName:   "waf_scan_event_list",
		RequestClass: "WafScanEventListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.scan.event.list",
		Title:        "扫描事件",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_scan_event_detail",
		MethodName:   "waf_scan_event_detail",
		RequestClass: "WafScanEventDetailRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.scan.event.detail",
		Title:        "扫描事件详情",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "waf_type_line",
		MethodName:   "waf_type_line",
		RequestClass: "WafTypeLineRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/stats_data.waf.type.line",
		Title:        "waf各类型攻击趋势",
		Source:       "scdn/statistical/scdn_dataapi_waf.php",
	},
	{
		APIName:      "LogDownloadTask_taskList",
		MethodName:   "log_download_task_task_list",
		RequestClass: "LogDownloadTaskTaskListRequest",
		Methods:      []string{"POST", "GET"},
		Path:         "/api/v5/soc.log.download.task.list",
		Title:        "查询日志下载任务列表",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTask_addTask",
		MethodName:   "log_download_task_add_task",
		RequestClass: "LogDownloadTaskAddTaskRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.task.add",
		Title:        "添加日志下载任务",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTask_cancelTask",
		MethodName:   "log_download_task_cancel_task",
		RequestClass: "LogDownloadTaskCancelTaskRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.task.cancel",
		Title:        "取消日志下载任务",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTask_batchCancelTask",
		MethodName:   "log_download_task_batch_cancel_task",
		RequestClass: "LogDownloadTaskBatchCancelTaskRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/soc.log.download.task.batch.cancel",
		Title:        "批量取消日志下载任务",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTask_deleteTask",
		MethodName:   "log_download_task_delete_task",
		RequestClass: "LogDownloadTaskDeleteTaskRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/soc.log.download.task.del",
		Title:        "删除日志下载任务",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTask_batchDeleteTask",
		MethodName:   "log_download_task_batch_delete_task",
		RequestClass: "LogDownloadTaskBatchDeleteTaskRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/soc.log.download.task.batch.del",
		Title:        "批量删除日志下载任务",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTask_regenerateTask",
		MethodName:   "log_download_task_regenerate_task",
		RequestClass: "LogDownloadTaskRegenerateTaskRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.task.regenerate",
		Title:        "重新生成日志下载任务",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadFieldConf_downloadFields",
		MethodName:   "log_download_field_conf_download_fields",
		RequestClass: "LogDownloadFieldConfDownloadFieldsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/soc.log.download.fields",
		Title:        "查询日志下载字段列表",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_templateList",
		MethodName:   "log_download_template_template_list",
		RequestClass: "LogDownloadTemplateTemplateListRequest",
		Methods:      []string{"POST", "GET"},
		Path:         "/api/v5/soc.log.download.template.list",
		Title:        "查询日志下载模板列表",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_getTemplateDomainList",
		MethodName:   "log_download_template_get_template_domain_list",
		RequestClass: "LogDownloadTemplateGetTemplateDomainListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/soc.log.download.template.domain.list",
		Title:        "查询日志下载模板选择域名列表",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_addTemplate",
		MethodName:   "log_download_template_add_template",
		RequestClass: "LogDownloadTemplateAddTemplateRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.template.add",
		Title:        "新增日志下载模板",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_saveTemplate",
		MethodName:   "log_download_template_save_template",
		RequestClass: "LogDownloadTemplateSaveTemplateRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.template.save",
		Title:        "修改日志下载模板",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_delTemplate",
		MethodName:   "log_download_template_del_template",
		RequestClass: "LogDownloadTemplateDelTemplateRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/soc.log.download.template.del",
		Title:        "删除日志下载模板",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_batchDelTemplate",
		MethodName:   "log_download_template_batch_del_template",
		RequestClass: "LogDownloadTemplateBatchDelTemplateRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/soc.log.download.template.batch.del",
		Title:        "批量删除日志下载模板",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_changeStatus",
		MethodName:   "log_download_template_change_status",
		RequestClass: "LogDownloadTemplateChangeStatusRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.template.change.status",
		Title:        "更改日志下载模板状态",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_batchChangeStatus",
		MethodName:   "log_download_template_batch_change_status",
		RequestClass: "LogDownloadTemplateBatchChangeStatusRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/soc.log.download.template.batch.change.status",
		Title:        "批量更改日志下载模板状态",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_allTemplate",
		MethodName:   "log_download_template_all_template",
		RequestClass: "LogDownloadTemplateAllTemplateRequest",
		Methods:      []string{"POST", "GET"},
		Path:         "/api/v5/soc.log.download.template.all",
		Title:        "查询日志下载模板列表（添加任务时使用）",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "LogDownloadTemplate_allTemplateGroup",
		MethodName:   "log_download_template_all_template_group",
		RequestClass: "LogDownloadTemplateAllTemplateGroupRequest",
		Methods:      []string{"POST", "GET"},
		Path:         "/api/v5/soc.log.download.template.group.all",
		Title:        "查询日志下载模板分组列表（搜索或添加模板使用）",
		Source:       "scdn/statistical/scdn_soc_log_download.php",
	},
	{
		APIName:      "TjkdPlusPackage_getMemberPackageList",
		MethodName:   "tjkd_plus_package_get_member_package_list",
		RequestClass: "TjkdPlusPackageGetMemberPackageListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.package.list",
		Title:        "查询独享IP资源包列表",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_getAllPackage",
		MethodName:   "tjkd_plus_package_get_all_package",
		RequestClass: "TjkdPlusPackageGetAllPackageRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.package.all",
		Title:        "查询独享IP资源包列表(简)",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_getPackageInfo",
		MethodName:   "tjkd_plus_package_get_package_info",
		RequestClass: "TjkdPlusPackageGetPackageInfoRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/tjkd.plus.package.info",
		Title:        "查询独享IP资源包详情",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_getPackageIpList",
		MethodName:   "tjkd_plus_package_get_package_ip_list",
		RequestClass: "TjkdPlusPackageGetPackageIpListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.package.ip.list",
		Title:        "查询独享IP资源包IP列表",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_getPackageOverview",
		MethodName:   "tjkd_plus_package_get_package_overview",
		RequestClass: "TjkdPlusPackageGetPackageOverviewRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.package.overview",
		Title:        "独享IP资源包总览",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_getPackagePortList",
		MethodName:   "tjkd_plus_package_get_package_port_list",
		RequestClass: "TjkdPlusPackageGetPackagePortListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/tjkd.plus.package.port.list",
		Title:        "查询独享IP资源包的转发端口列表",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_savePackage",
		MethodName:   "tjkd_plus_package_save_package",
		RequestClass: "TjkdPlusPackageSavePackageRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/tjkd.plus.package.save",
		Title:        "修改独享IP资源包名称",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_savePackageHealthyConf",
		MethodName:   "tjkd_plus_package_save_package_healthy_conf",
		RequestClass: "TjkdPlusPackageSavePackageHealthyConfRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/tjkd.plus.package.save.healthy.conf",
		Title:        "保存独享IP资源包回源配置",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusForwardRule_savePlusForwardRule",
		MethodName:   "tjkd_plus_forward_rule_save_plus_forward_rule",
		RequestClass: "TjkdPlusForwardRuleSavePlusForwardRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Tjkd.plus.forward.rule.save",
		Title:        "保存转发规则",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusForwardRule_batchAddPlusForwardRule",
		MethodName:   "tjkd_plus_forward_rule_batch_add_plus_forward_rule",
		RequestClass: "TjkdPlusForwardRuleBatchAddPlusForwardRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Tjkd.plus.forward.rule.batch.add",
		Title:        "添加转发规则",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusForwardRule_batchSavePlusForwardRule",
		MethodName:   "tjkd_plus_forward_rule_batch_save_plus_forward_rule",
		RequestClass: "TjkdPlusForwardRuleBatchSavePlusForwardRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Tjkd.plus.forward.rule.batch.save",
		Title:        "修改转发规则(批量)",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusForwardRule_delPlusForwardRule",
		MethodName:   "tjkd_plus_forward_rule_del_plus_forward_rule",
		RequestClass: "TjkdPlusForwardRuleDelPlusForwardRuleRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/Tjkd.plus.forward.rule.del",
		Title:        "删除转发规则",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusForwardRule_getPlusForwardRuleList",
		MethodName:   "tjkd_plus_forward_rule_get_plus_forward_rule_list",
		RequestClass: "TjkdPlusForwardRuleGetPlusForwardRuleListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.forward.rule.list",
		Title:        "查询转发规则列表",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusForwardRule_getBatchPlusForwardRuleInfo",
		MethodName:   "tjkd_plus_forward_rule_get_batch_plus_forward_rule_info",
		RequestClass: "TjkdPlusForwardRuleGetBatchPlusForwardRuleInfoRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Tjkd.plus.forward.rule.batch.info",
		Title:        "查询转发规则列表",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusPackage_getPackageDomainList",
		MethodName:   "tjkd_plus_package_get_package_domain_list",
		RequestClass: "TjkdPlusPackageGetPackageDomainListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.package.domain.list",
		Title:        "查询使用独享IP资源包的域名列表(简)",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusDomain_getTjkdPlusDomainList",
		MethodName:   "tjkd_plus_domain_get_tjkd_plus_domain_list",
		RequestClass: "TjkdPlusDomainGetTjkdPlusDomainListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/Tjkd.plus.domain.list",
		Title:        "查询使用独享IP资源包的域名列表",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusDomain_addTjkdPlusDomain",
		MethodName:   "tjkd_plus_domain_add_tjkd_plus_domain",
		RequestClass: "TjkdPlusDomainAddTjkdPlusDomainRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/Tjkd.plus.domain.add",
		Title:        "域名绑定独享IP资源包",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "TjkdPlusDomain_delTjkdPlusDomain",
		MethodName:   "tjkd_plus_domain_del_tjkd_plus_domain",
		RequestClass: "TjkdPlusDomainDelTjkdPlusDomainRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/Tjkd.plus.domain.del",
		Title:        "域名解绑独享IP资源包",
		Source:       "scdn/tcp/scdn_domain_tcp.php",
	},
	{
		APIName:      "NetworkSpeedGetCacheRuleList",
		MethodName:   "network_speed_get_cache_rule_list",
		RequestClass: "NetworkSpeedGetCacheRuleListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/ruletpl/cache/rules",
		Title:        "获取缓存规则列表",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedCreateCacheRule",
		MethodName:   "network_speed_create_cache_rule",
		RequestClass: "NetworkSpeedCreateCacheRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/ruletpl/cache/rules",
		Title:        "创建缓存规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedUpdateCacheRule",
		MethodName:   "network_speed_update_cache_rule",
		RequestClass: "NetworkSpeedUpdateCacheRuleRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/cache/rule",
		Title:        "编辑缓存规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedUpdateCacheRuleConfig",
		MethodName:   "network_speed_update_cache_rule_config",
		RequestClass: "NetworkSpeedUpdateCacheRuleConfigRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/cache/rule/conf",
		Title:        "编辑缓存规则配置",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedUpdateCacheRuleStatus",
		MethodName:   "network_speed_update_cache_rule_status",
		RequestClass: "NetworkSpeedUpdateCacheRuleStatusRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/cache/rule_status",
		Title:        "启用或禁用缓存规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedSortCacheRules",
		MethodName:   "network_speed_sort_cache_rules",
		RequestClass: "NetworkSpeedSortCacheRulesRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/cache/rule_sort",
		Title:        "缓存规则排序",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedGetGlobalCacheConfig",
		MethodName:   "network_speed_get_global_cache_config",
		RequestClass: "NetworkSpeedGetGlobalCacheConfigRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/ruletpl/cache/global/conf",
		Title:        "获取默认全局缓存配置",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedDeleteCacheRule",
		MethodName:   "network_speed_delete_cache_rule",
		RequestClass: "NetworkSpeedDeleteCacheRuleRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/ruletpl/cache/rule",
		Title:        "删除缓存规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedGetTemplateConfig",
		MethodName:   "network_speed_get_template_config",
		RequestClass: "NetworkSpeedGetTemplateConfigRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/ruletpl/network_speed/get_conf",
		Title:        "获取模版配置",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedUpdateTemplateConfig",
		MethodName:   "network_speed_update_template_config",
		RequestClass: "NetworkSpeedUpdateTemplateConfigRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/network_speed/conf",
		Title:        "修改模版配置",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedGetRules",
		MethodName:   "network_speed_get_rules",
		RequestClass: "NetworkSpeedGetRulesRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/ruletpl/network_speed/rules",
		Title:        "获取配置规则列表",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedCreateRule",
		MethodName:   "network_speed_create_rule",
		RequestClass: "NetworkSpeedCreateRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/ruletpl/network_speed/rules",
		Title:        "创建配置规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedDeleteRule",
		MethodName:   "network_speed_delete_rule",
		RequestClass: "NetworkSpeedDeleteRuleRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/ruletpl/network_speed/rule",
		Title:        "删除配置规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedSortRules",
		MethodName:   "network_speed_sort_rules",
		RequestClass: "NetworkSpeedSortRulesRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/network_speed/rule_sort",
		Title:        "配置规则集排序",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "NetworkSpeedUpdateRule",
		MethodName:   "network_speed_update_rule",
		RequestClass: "NetworkSpeedUpdateRuleRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpl/network_speed/rule",
		Title:        "编辑配置规则",
		Source:       "scdn/tpl_rule/scdn_domain_network_speed.php",
	},
	{
		APIName:      "UpdateRuleTemplate",
		MethodName:   "update_rule_template",
		RequestClass: "UpdateRuleTemplateRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpls",
		Title:        "更新模版",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl.php",
	},
	{
		APIName:      "DeleteRuleTemplate",
		MethodName:   "delete_rule_template",
		RequestClass: "DeleteRuleTemplateRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/ruletpls",
		Title:        "删除模版",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl.php",
	},
	{
		APIName:      "GetRuleTemplateList",
		MethodName:   "get_rule_template_list",
		RequestClass: "GetRuleTemplateListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/ruletpls",
		Title:        "获取模版列表",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl.php",
	},
	{
		APIName:      "UnbindRuleTemplate",
		MethodName:   "unbind_rule_template",
		RequestClass: "UnbindRuleTemplateRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpls/unbind_domain",
		Title:        "域名解绑模版",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl.php",
	},
	{
		APIName:      "BindRuleTemplate",
		MethodName:   "bind_rule_template",
		RequestClass: "BindRuleTemplateRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpls/bind_domain",
		Title:        "域名绑定模版",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl.php",
	},
	{
		APIName:      "ListRuleTpsDomains",
		MethodName:   "list_rule_tps_domains",
		RequestClass: "ListRuleTpsDomainsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/ruletpls/domains",
		Title:        "获取模版绑定的域名",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl.php",
	},
	{
		APIName:      "CreateRuleTemplate",
		MethodName:   "create_rule_template",
		RequestClass: "CreateRuleTemplateRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/ruletpls",
		Title:        "创建模版",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl_pr.php",
	},
	{
		APIName:      "SwitchDomainTemplate",
		MethodName:   "switch_domain_template",
		RequestClass: "SwitchDomainTemplateRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/ruletpls/domain/switch_tpl",
		Title:        "切换域名模版",
		Source:       "scdn/tpl_rule/scdn_domain_network_tpl_pr.php",
	},
	{
		APIName:      "Firewall_pageCfg",
		MethodName:   "firewall_page_cfg",
		RequestClass: "FirewallPageCfgRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.pagecfg",
		Title:        "获取可用策略规则",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_pageCfgHwws",
		MethodName:   "firewall_page_cfg_hwws",
		RequestClass: "FirewallPageCfgHwwsRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.pagecfg.hwws",
		Title:        "获取可用策略规则通过模板ID",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_savePolicy",
		MethodName:   "firewall_save_policy",
		RequestClass: "FirewallSavePolicyRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.save",
		Title:        "保存策略",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_getPolicy",
		MethodName:   "firewall_get_policy",
		RequestClass: "FirewallGetPolicyRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.get_id",
		Title:        "查询策略通过策略ID",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_getPolicyByCode",
		MethodName:   "firewall_get_policy_by_code",
		RequestClass: "FirewallGetPolicyByCodeRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.get_code",
		Title:        "查询策略通过策略CODE",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_statsPolicy",
		MethodName:   "firewall_stats_policy",
		RequestClass: "FirewallStatsPolicyRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.stats_domainid",
		Title:        "统计策略",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_open",
		MethodName:   "firewall_open",
		RequestClass: "FirewallOpenRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.open",
		Title:        "启用策略",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_stop",
		MethodName:   "firewall_stop",
		RequestClass: "FirewallStopRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.stop",
		Title:        "暂停策略",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_delete",
		MethodName:   "firewall_delete",
		RequestClass: "FirewallDeleteRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.delete",
		Title:        "删除策略",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_sort",
		MethodName:   "firewall_sort",
		RequestClass: "FirewallSortRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.sort",
		Title:        "策略排序",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_getsPolicyByMainid",
		MethodName:   "firewall_gets_policy_by_mainid",
		RequestClass: "FirewallGetsPolicyByMainidRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.get_mainid",
		Title:        "查询策略历史",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_getsPolicyByPackageid",
		MethodName:   "firewall_gets_policy_by_packageid",
		RequestClass: "FirewallGetsPolicyByPackageidRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.get_packageid",
		Title:        "查询策略通过独享资源包ID",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_savePolicyGroup",
		MethodName:   "firewall_save_policy_group",
		RequestClass: "FirewallSavePolicyGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.save",
		Title:        "保存策略集",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_getsPolicyGroupByDomainid",
		MethodName:   "firewall_gets_policy_group_by_domainid",
		RequestClass: "FirewallGetsPolicyGroupByDomainidRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policyGroup.get_domainid",
		Title:        "查询策略集通过模版ID",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_stopGroup",
		MethodName:   "firewall_stop_group",
		RequestClass: "FirewallStopGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.stop",
		Title:        "暂停策略集",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_openGroup",
		MethodName:   "firewall_open_group",
		RequestClass: "FirewallOpenGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.open",
		Title:        "启用策略集",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_deleteGroup",
		MethodName:   "firewall_delete_group",
		RequestClass: "FirewallDeleteGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.delete",
		Title:        "删除策略集",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_sortGroup",
		MethodName:   "firewall_sort_group",
		RequestClass: "FirewallSortGroupRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.sort",
		Title:        "策略集排序",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "Firewall_getsPolicyByGroupId",
		MethodName:   "firewall_gets_policy_by_group_id",
		RequestClass: "FirewallGetsPolicyByGroupIdRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.get_groupId",
		Title:        "查询策略集",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "getPolicyGroupTPL",
		MethodName:   "get_policy_group_tpl",
		RequestClass: "GetPolicyGroupTplRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policyGroup.tpl.get",
		Title:        "查询引用规则集列表",
		Source:       "scdn/tpl_rule/scdn_firewall_policy.php",
	},
	{
		APIName:      "GetDdosProtectionConfig",
		MethodName:   "get_ddos_protection_config",
		RequestClass: "GetDdosProtectionConfigRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/security_protection/ddos/configs",
		Title:        "获取DDoS防护配置",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "UpdateDdosProtectionConfig",
		MethodName:   "update_ddos_protection_config",
		RequestClass: "UpdateDdosProtectionConfigRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/security_protection/ddos/configs",
		Title:        "更新DDoS防护配置",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "GetWafRuleConfig",
		MethodName:   "get_waf_rule_config",
		RequestClass: "GetWafRuleConfigRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/security_protection/waf/rules",
		Title:        "获取WAF规则配置",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "UpdateWafRuleConfig",
		MethodName:   "update_waf_rule_config",
		RequestClass: "UpdateWafRuleConfigRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/security_protection/waf/rules",
		Title:        "更新WAF规则配置",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "GetMemberGlobalTemplate",
		MethodName:   "get_member_global_template",
		RequestClass: "GetMemberGlobalTemplateRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/security_protection/template/member/global",
		Title:        "获取用户全局模板",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "CreateTemplate",
		MethodName:   "create_template",
		RequestClass: "CreateTemplateRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template",
		Title:        "创建模板",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "CreateDomainTemplate",
		MethodName:   "create_domain_template",
		RequestClass: "CreateDomainTemplateRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template/domain",
		Title:        "创建域名模板",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "GetTemplateList",
		MethodName:   "get_template_list",
		RequestClass: "GetTemplateListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template/search",
		Title:        "获取模板列表",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "GetTemplateBindDomainList",
		MethodName:   "get_template_bind_domain_list",
		RequestClass: "GetTemplateBindDomainListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template/domain/bind/search",
		Title:        "获取模板绑定域名",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "BindTemplateDomain",
		MethodName:   "bind_template_domain",
		RequestClass: "BindTemplateDomainRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template/domain/bind",
		Title:        "模板绑定域名",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "DeleteTemplate",
		MethodName:   "delete_template",
		RequestClass: "DeleteTemplateRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/security_protection/template",
		Title:        "删除模板",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "BatchConfigTemplate",
		MethodName:   "batch_config_template",
		RequestClass: "BatchConfigTemplateRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template/batch/config",
		Title:        "模板批量配置",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "Iota",
		MethodName:   "iota",
		RequestClass: "IotaRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/security_protection/template/iota",
		Title:        "获取枚举值",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "GetUnboundTemplateDomainList",
		MethodName:   "get_unbound_template_domain_list",
		RequestClass: "GetUnboundTemplateDomainListRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/security_protection/template/domain/unbound/search",
		Title:        "获取未绑定模板域名",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "EditTemplate",
		MethodName:   "edit_template",
		RequestClass: "EditTemplateRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/security_protection/template",
		Title:        "编辑模板",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "Firewall_savePolicyGroupRegionalShielding",
		MethodName:   "firewall_save_policy_group_regional_shielding",
		RequestClass: "FirewallSavePolicyGroupRegionalShieldingRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.save",
		Title:        "开启区域屏蔽",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "Firewall_savePolicyGroupAntiLeech",
		MethodName:   "firewall_save_policy_group_anti_leech",
		RequestClass: "FirewallSavePolicyGroupAntiLeechRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policyGroup.save",
		Title:        "开启防盗链",
		Source:       "scdn/tpl_rule/scdn_security_protection.php",
	},
	{
		APIName:      "TjkdappsaveFirewallPolicy",
		MethodName:   "tjkdappsave_firewall_policy",
		RequestClass: "TjkdappsaveFirewallPolicyRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.save",
		Title:        "保存精准访问控制策略",
		Source:       "sdk/tjkd_app_acl.php",
	},
	{
		APIName:      "TjkdappsortFirewallPolicy",
		MethodName:   "tjkdappsort_firewall_policy",
		RequestClass: "TjkdappsortFirewallPolicyRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.sort",
		Title:        "排序精准访问控制策略",
		Source:       "sdk/tjkd_app_acl.php",
	},
	{
		APIName:      "TjkdappopenFirewallPolicy",
		MethodName:   "tjkdappopen_firewall_policy",
		RequestClass: "TjkdappopenFirewallPolicyRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.open",
		Title:        "启动精准访问控制策略",
		Source:       "sdk/tjkd_app_acl.php",
	},
	{
		APIName:      "TjkdappstopFirewallPolicy",
		MethodName:   "tjkdappstop_firewall_policy",
		RequestClass: "TjkdappstopFirewallPolicyRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.stop",
		Title:        "暂停精准访问控制策略",
		Source:       "sdk/tjkd_app_acl.php",
	},
	{
		APIName:      "TjkdappgetFirewallPolicy",
		MethodName:   "tjkdappget_firewall_policy",
		RequestClass: "TjkdappgetFirewallPolicyRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/firewall.policy.get_tjkdappid",
		Title:        "获取精准访问控制策略列表",
		Source:       "sdk/tjkd_app_acl.php",
	},
	{
		APIName:      "TjkdappdeleteFirewallPolicy",
		MethodName:   "tjkdappdelete_firewall_policy",
		RequestClass: "TjkdappdeleteFirewallPolicyRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/firewall.policy.delete",
		Title:        "删除精准访问控制策略",
		Source:       "sdk/tjkd_app_acl.php",
	},
	{
		APIName:      "addForwardRule",
		MethodName:   "add_forward_rule",
		RequestClass: "AddForwardRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/tjkd.app.domain.add",
		Title:        "添加转发规则",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "deleteForwardRule",
		MethodName:   "delete_forward_rule",
		RequestClass: "DeleteForwardRuleRequest",
		Methods:      []string{"DELETE"},
		Path:         "/api/v5/tjkd.app.domain.del",
		Title:        "删除转发规则",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "editRule",
		MethodName:   "edit_rule",
		RequestClass: "EditRuleRequest",
		Methods:      []string{"POST"},
		Path:         "/api/v5/tjkd.app.domain.edit",
		Title:        "修改规则",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "ruleList",
		MethodName:   "rule_list",
		RequestClass: "RuleListRequest",
		Methods:      []string{"GET", "POST"},
		Path:         "/api/v5/tjkd.app.domain.list",
		Title:        "规则列表",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "getRuleInfo",
		MethodName:   "get_rule_info",
		RequestClass: "GetRuleInfoRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/tjkd.app.domain.info",
		Title:        "获取规则详情",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "TIJKDAPP_ListPackage",
		MethodName:   "tijkdapp_list_package",
		RequestClass: "TijkdappListPackageRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/tjkd.app.package.list",
		Title:        "套餐列表",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "TIJKDAPP_SavePackage",
		MethodName:   "tijkdapp_save_package",
		RequestClass: "TijkdappSavePackageRequest",
		Methods:      []string{"PUT"},
		Path:         "/api/v5/tjkd.app.package.save",
		Title:        "套餐名称修改",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "getChannelList",
		MethodName:   "get_channel_list",
		RequestClass: "GetChannelListRequest",
		Methods:      []string{"GET"},
		Path:         "/api/v5/tjkd.app.package.channel.list",
		Title:        "套餐加速通道列表",
		Source:       "sdk/tjkd_app_rule_pr.php",
	},
	{
		APIName:      "api_name_v5",
		MethodName:   "api_name_v5",
		RequestClass: "ApiNameV5Request",
		Methods:      []string{"POST"},
		Path:         "/api/v5/api对应路由NAME",
		Title:        "SDK API 5.0.0示例",
		Source:       "sdk_example_pr.php",
	},
}
